[ -z $ENVIRONMENT ] && export ENVIRONMENT="example"
[ -z $DOMAIN ] && export DOMAIN="example.com"
[ -z $SHARD_BASE ] && export SHARD_BASE="example"
[ -z $SSL_CERTIFICATE_ID ] && export SSL_CERTIFICATE_ID="star_example_com-2023-08-19"
export JVB_HEALTH_SNS="ExampleCom-Health-Check-List"
export JVB_ASG_SNS="ExampleCom-ASG-alarms"
export JVB_DEFAULT_AUTOSCALER_ENABLED="true"
export JIBRI_DEFAULT_AUTOSCALER_ENABLED="true"
export COTURN_HEALTH_SNS="$JVB_HEALTH_SNS"
export COTURN_ASG_SNS="$JVB_ASG_SNS"
export JIGASI_MIN_COUNT=1
export DEFAULT_JIBRI_MIN_COUNT=1
export JIGASI_HAPROXY_MIN_COUNT=1
export JIGASI_HAPROXY_ENABLED="true"
export ENABLE_PAGERDUTY_ALARMS="false"
export RELEASE_CLOUDS="us-west-2-dev1"
export USE_EIP="false"
export DEFAULT_AUTOSCALER_JVB_POOL_SIZE=3
export DEFAULT_AUTOSCALER_JIGASI_POOL_SIZE=1
export AUTOSCALER_JVB_MAX_COUNT=5
export SIDECAR_ENV_VARIABLES="pilot.env"
export TOKEN_GENERATOR_ENV_VARIABLES="pilot.env"
export DRG_PEER_REGIONS="us-phoenix-1 eu-frankfurt-1"
export COMPARTMENT_OCID="ocid1.compartment.oc1..aaaaaaaaaaexampleaaaaaaaaaaaaaaaaaaa"
export AUTOSCALER_URL="https://jitsi-autoscaler.example.com"
export JIBRI_ENABLE_RECONFIGURATION=true
export JIGASI_ENABLE_RECONFIGURATION=true
export TURN_TCP_HEALTH_CHECKS="true"
export AWS_CONSUL_ENV="dev"
export AWS_LOCAL_DATACENTER="us-west-2-dev1"
export ENVIRONMENT_TYPE="dev"
export CONSUL_INCLUDE_AWS="false"
